language: objective-c
osx_image: xcode12.2

cache:
  directories:
  - Carthage

before_script:
    - travis_wait 30 ./bin/carthage bootstrap --use-xcframeworks --cache-builds

script:
    # Build frameworks and run tests
    - xcodebuild -project CGMBLEKit.xcodeproj -scheme Shared build -destination name="iPhone 8" test 
    # Build apps
    - xcodebuild -project CGMBLEKit.xcodeproj -scheme "CGMBLEKit Example" build -destination name="iPhone 8"
    - xcodebuild -project CGMBLEKit.xcodeproj -scheme ResetTransmitter build -destination name="iPhone 8"

